receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://localhost:3000"

processors:
  batch: {}

extensions:
  basicauth/otlp:
    client_auth:
      username: <redacted>
      password: <redacted>

exporters:
  otlphttp:
    endpoint: https://otlp-gateway-prod-sa-east-0.grafana.net/otlp
    auth:
      authenticator: basicauth/otlp
      

service:
  extensions: [basicauth/otlp]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]